version: '2'

services:
    client:
        image: raivieiraadriano92/node-tools:latest
        volumes:
            - ./client:/home/app
        ports:
            - "3000:3000"
            - "3001:3001"
        tty: true